version: '3'
services:
  # mongodb:
  #   image: mongo:latest
  #   container_name: mongodb
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb-data:/data/db

  expressjs:
    build:
      context: ./express-app  # Path to the directory containing the Dockerfile for Express.js
    container_name: expressjs-final
    ports:
      - "3000:3000"
    # environment:
    #   MONGODB_URI: mongodb://mongodb:27017/userdb
    #   NODE_ENV: development
    command: bash -c "npm install -y && npm start"
    volumes:
      - ./express-app:/app
    # depends_on:
    #   - mongodb

# volumes:
#   mongodb-data:

