apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs-pod # Match the labels of your Node.js pod
  ports:
    - protocol: TCP
      port: 80 # The port to access the service from outside the cluster
      targetPort: 3000 # The port your Node.js application is running on inside the pod
  type: NodePort # Expose the service on a random port on all nodes
