version: '3'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana-container
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=mysecretpassword # Change this to your desired admin password
    volumes:
      - grafana_data:/var/lib/grafana
    # networks:
    #   - monitoring-net
    # ports:
    #   - "3000:3000"
    network_mode: "host"  # Use the host network for Grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus-container
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    # ports:
    #   - "9090:9090"
    # networks:
    #   - monitoring-net
    network_mode: "host"  # Use the host network for Prometheus

networks:
  monitoring-net:

volumes:
  grafana_data:
